/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Absolutevalue extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
               <path d="M14.5,32.5h1v-18h-1V32.5z M31.5,14.5v18h1v-18H31.5z M17.5,29.5h12v-12h-12V29.5z M19.5,19.5h8v8h-8V19.5z"/>
			</svg>
        )
    }
}

module.exports = Absolutevalue;
