/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Alpha extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M29.799,20.441v-2.053c-0.6,0.426-1.753,1.233-2.361,2.272c-0.913-1.621-2.401-2.691-4.177-2.691
                    c-2.817,0-5.062,2.686-5.062,6s2.302,6,5.119,6c1.75,0,3.153-1.038,4.071-2.619c0.609,1.075,1.811,1.914,2.411,2.35v-2.053
                    c-0.6-0.733-1.611-2.071-1.611-3.604C28.188,22.51,29.2,21.174,29.799,20.441z M23.335,28.168c-1.823,0-3.3-1.88-3.3-4.2
                    s1.477-4.2,3.3-4.2c1.823,0,3.3,1.88,3.3,4.2C26.636,26.288,25.159,28.168,23.335,28.168z"/>
			</svg>
        )
    }
}

module.exports = Alpha;
