/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Bai extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M22.408,19.112c0-1.657-1.343-3-3-3s-3,1.343-3,3s1.343,3,3,3C21.065,22.112,22.408,20.769,22.408,19.112z M18.208,19.112
                    c0-0.663,0.537-1.2,1.2-1.2s1.2,0.537,1.2,1.2s-0.537,1.2-1.2,1.2C18.745,20.312,18.208,19.775,18.208,19.112z M28.408,24.512
                    c-1.657,0-3,1.343-3,3s1.343,3,3,3s3-1.343,3-3S30.065,24.512,28.408,24.512z M28.408,28.712c-0.663,0-1.2-0.537-1.2-1.2
                    s0.537-1.2,1.2-1.2s1.2,0.537,1.2,1.2S29.071,28.712,28.408,28.712z M27.811,15L17.419,33h2.078l10.392-18H27.811z"/>
			</svg>
        )
    }
}

module.exports = Bai;
