/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Bar extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M18,15.6v1.8h12v-1.8H18z M18,32.4h12v-12H18V32.4z M19.8,22.2h8.4v8.4h-8.4V22.2z"/>
			</svg>
        )
    }
}

module.exports = Bar;
