/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Beta extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M26.288,21.278c0.779-0.759,1.263-1.818,1.263-2.992c0-2.309-1.876-4.181-4.185-4.181s-4.158,1.885-4.158,4.194
                    c0,0.186,0,15.597,0,15.597h2v-4.689c0,0.64,1.74,1.026,2.854,1.026c2.639,0,4.731-2.139,4.731-4.778
                    C28.792,23.657,27.753,22.094,26.288,21.278z M24.006,28.59c-1.445,0-2.798-1.045-2.798-2.24l0,0v-7.765l0,0
                    c0-1.792,0.882-2.538,2.201-2.538s2.37,0.995,2.37,2.314c0,1.319-0.881,2.352-2.2,2.352c-0.194,0-0.371-0.067-0.371-0.11V22.7
                    c0-0.15,0.548-0.233,0.958-0.233c1.649,0,2.906,1.412,2.906,3.061S25.656,28.59,24.006,28.59z"/>
			</svg>
        )
    }
}

module.exports = Beta;
