/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Cos extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
				<g>
					<path d="M23.039,15.938c-0.292-0.09-0.592-0.142-0.9-0.142c-2.665,0-4.825,3.538-4.825,7.902s2.16,7.902,4.825,7.902
						c0.308,0,0.608-0.052,0.9-0.142c-2.234-0.691-3.925-3.9-3.925-7.76S20.805,16.629,23.039,15.938z"/>
					<path d="M26.014,15.795c-0.308,0-0.608,0.052-0.9,0.142c2.234,0.691,3.925,3.9,3.925,7.76s-1.691,7.069-3.925,7.76
						c0.292,0.09,0.592,0.142,0.9,0.142c2.665,0,4.825-3.538,4.825-7.902S28.679,15.795,26.014,15.795z"/>
				</g>
			</svg>
        )
    }
}

module.exports = Cos;
