/**
 * An autogenerated component that renders the CDOT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Cdots extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
            <g id="图层_1_1_">
                <g>
                    <circle cx="17.346" cy="24" r="1.8"/>
                    <circle cx="23.983" cy="24" r="1.8"/>
                    <circle cx="30.621" cy="24" r="1.8"/>
                </g>
            </g>
        </svg>;
    }
}

module.exports = Cdots;
