/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Colon extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24,22.06c1.548,0,2.803-1.255,2.803-2.803S25.548,16.454,24,16.454s-2.803,1.255-2.803,2.803
                    C21.197,20.805,22.452,22.06,24,22.06z M24,26.031c-1.548,0-2.803,1.255-2.803,2.803s1.255,2.803,2.803,2.803
                    s2.803-1.255,2.803-2.803C26.803,27.285,25.548,26.031,24,26.031z"/>
			</svg>
        )
    }
}

module.exports = Colon;
