/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Comma extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
			<svg width="48" height="48" viewBox="0 0 48 48">
				<path d="M27.141,23.493c0-1.332-1.08-2.412-2.412-2.412c-1.332,0-2.412,1.08-2.412,2.412c0,1.166,0.828,2.139,1.928,2.363
	c-0.58,1.411-1.439,2.536-2.548,3.207c0.425-0.006,0.847-0.055,1.26-0.173c1.845-0.529,3.224-2.074,3.952-4.253
	C27.038,24.207,27.141,23.845,27.141,23.493z"/>
			</svg>
		)
    }
}

module.exports = Comma;
