/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Comma extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
			<svg width="48" height="48" viewBox="0 0 48 48">
				<path d="M27.103,22.948c0-1.657-1.343-2.95-3-2.95c-1.657,0-3,1.368-3,3.025c0,1.551,1.182,2.825,2.692,2.981
					c-0.753,0.617-1.737,1.056-2.843,1.21c0.293,0.041,0.593-0.031,0.9-0.031c2.845,0,5.156-2.184,5.243-4.184h-0.007
					C27.09,23,27.103,23,27.103,22.948z"/>
			</svg>
		)
    }
}

module.exports = Comma;
