/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Complement extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M23.863,31.664c-1.657,0-2.863-1.287-2.863-2.944v-9.6c0-1.657,1.343-3,3-3s3,1.343,3,3v0.488h2V19.12
                    c0-2.651-2.349-4.8-5-4.8s-5,2.149-5,4.8v9.6c0,2.651,2.112,4.744,4.763,4.744s4.763-1.856,4.763-4.856h-1.8
                    C26.725,30.608,25.519,31.664,23.863,31.664z"/>
			</svg>
        )
    }
}

module.exports = Complement;
