/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Cup extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M29.031,14.5v11.824c0,2.973-2.027,5.382-5,5.382s-5-2.41-5-5.382V14.5h-2v11.824c0,3.963,3.037,7.176,7,7.176
	s7-3.213,7-7.176V14.5H29.031z"/>
			</svg>
        )
    }
}

module.exports = Cup;
