/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Delta extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24,17.35l-7.8,13.2h15.6L24,17.35z M24.008,20.75l4.492,7.8h-9L24.008,20.75z"/>
			</svg>
        )
    }
}

module.exports = Delta;
