/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Dwan extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M27.956,24.34c-0.183-0.207-0.378-0.412-0.583-0.617c-0.884-0.881-1.957-1.733-3.189-2.484
                    c-1.517-0.925-3.057-1.564-4.478-1.924l-0.411,0.854c1.214,0.788,2.45,1.868,3.577,3.202c0.786,0.929,1.443,1.891,1.966,2.839
                    c0.41,0.743,0.579,1.55,1.004,2.1c0.247,0.183,0.491,0.375,0.788,0.375c0.994,0,1.8-1.164,1.8-2.6
                    C28.43,25.411,28.342,24.836,27.956,24.34z"/>
			</svg>
        )
    }
}

module.exports = Dwan;
