/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Four extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24,15.484c-4.694,0-8.5,3.806-8.5,8.5c0,4.694,3.806,8.5,8.5,8.5c4.694,0,8.5-3.806,8.5-8.5
	C32.5,19.29,28.694,15.484,24,15.484z M24,31.225c-3.999,0-7.241-3.242-7.241-7.241c0-3.999,3.242-7.241,7.241-7.241
	s7.241,3.242,7.241,7.241C31.241,27.983,27.999,31.225,24,31.225z M25.792,18.817h-2.465l-3.866,6.275v1.4h4.413v2.689h1.919v-2.689
	h1.232v-1.568h-1.232V18.817z M23.873,22.81v2.115h-2.409l1.611-2.577c0.294-0.561,0.574-1.135,0.826-1.681h0.056
	C23.93,21.269,23.873,22.208,23.873,22.81z"/>
			</svg>
        )
    }
}

module.exports = Four;
