/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Gamma extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M29.411,16h-1.8c0,3-0.964,5.649-2.588,7.842C24.548,20.839,23.183,17,21.205,16h-2.616c2.944,2,4.783,5.603,4.783,9.712
	v1.796V32h2v-6.089C28.373,23.215,29.411,20,29.411,16z"/>
            </svg>;
    }
}

module.exports = Gamma;
