/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Hat extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M18,21.412v12h12v-12H18z M28.2,31.611h-8.4v-8.4h8.4V31.611z M29,19.421v-2.102l-4.859-2.749L19,17.579v2.102l5.225-3.015
	                L29,19.421z M24.081,14.571l0.054-0.005l-0.002-0.001L24.081,14.571z M24.135,14.567l0.006,0.003l0.008-0.005L24.135,14.567z"/>
            </svg>;
    }
}

module.exports = Hat;
