/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class In extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24.318,17.479h7.306v-2h-7.231c-4.206,0-8.266,3.083-8.266,7.083l0.055,1.935c0,4.286,4.005,7.982,8.211,7.982h7.231v-2
	                h-7.306c-3.186,0-5.811-2.571-6.219-6h13.525v-2H18.099C18.507,20.479,21.132,17.479,24.318,17.479z"/>
			</svg>
        )
    }
}

module.exports = In;
