/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Huo extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M28.069,19.451c-1.804,0-3.357,1.06-4.083,2.588c-0.736-1.498-2.273-2.532-4.056-2.532c-2.497,0-4.521,2.024-4.521,4.521
                    s2.024,4.521,4.521,4.521c1.804,0,3.357-1.06,4.083-2.588c0.736,1.498,2.273,2.532,4.056,2.532c2.497,0,4.521-2.024,4.521-4.521
                    S30.566,19.451,28.069,19.451z M19.931,26.741c-1.498,0-2.713-1.215-2.713-2.713s1.215-2.713,2.713-2.713s2.713,1.215,2.713,2.713
                    S21.429,26.741,19.931,26.741z M28.069,26.685c-1.498,0-2.713-1.215-2.713-2.713s1.215-2.713,2.713-2.713s2.713,1.215,2.713,2.713
                    S29.567,26.685,28.069,26.685z"/>
			</svg>
        )
    }
}

module.exports = Huo;
