/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Lambda extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M22.681,20.896l-3.786,10.603h1.915l2.936-8.31c0.189,0.468,2.557,6.311,3.591,8.311h2.203
	                c-0.906-1-3.693-8.299-3.693-8.299c-1.144-3-3.029-6.7-5.148-6.7h-2.238v2h1.315C21.082,18.499,21.948,19.573,22.681,20.896z"/>
			</svg>
        )
    }
}

module.exports = Lambda;
