/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Le extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <rect x="12.5" y="12.5" display="none" opacity="0.2" width="22" height="22"/>
                    <rect x="7.5" y="7.5" display="none" opacity="0.2" width="32" height="32"/>
                    <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                    <path d="M31.5,14.718l-16,6.126v1.543l0.114,0.188L31.5,28.518v-1.915l-13.678-4.978L31.5,16.64V14.718z M15.5,32.5h16v-2h-16V32.5
                        z"/>
                </g>
			</svg>
        )
    }
}

module.exports = Le;
