/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Leftright extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M27.277,15.408c-0.308,0-0.608,0.052-0.9,0.142c2.234,0.691,3.925,3.9,3.925,7.76s-1.691,7.069-3.925,7.76
                    c0.292,0.09,0.592,0.142,0.9,0.142c2.665,0,4.825-3.538,4.825-7.902S29.941,15.408,27.277,15.408z"/>
                <polygon points="15.5,15.5 15.5,17.412 15.5,29.412 15.5,31.5 17.977,31.5 20.5,31.5 20.5,29.5 17.5,29.5 17.5,17.5 20.5,17.5 
                    20.5,15.5 17.977,15.5 	"/>
			</svg>
        )
    }
}

module.exports = Leftright;
