/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Lg extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
            <path d="M18.659,28.736h2v-13h-2V28.736z M29.29,20.736h-1.631v0.219c0-0.355-1.137-0.562-1.791-0.562
                c-1.988,0-3.599,1.88-3.599,4.2s1.613,4.2,3.601,4.2c0.619,0,1.202-0.183,1.711-0.504c-0.024,1.283-0.899,2.175-1.71,2.175
                c-0.453,0-0.863,0.272-1.179-0.728h-2.07c0.578,1,1.814,2.528,3.249,2.528c0.654,0,1.265-0.142,1.794-0.498
                c1.045-0.703,1.7-1.761,1.675-3.83C29.34,27.888,29.29,20.736,29.29,20.736z M27.659,24.676c0,1.286-0.818,2.317-1.791,2.317
                c-0.994,0-1.799-1.075-1.799-2.4c0-1.326,0.804-2.4,1.798-2.4c0.973,0,1.792,1.031,1.792,2.317V24.676z"/>
        </svg>;
    }
}

module.exports = Lg;
