/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Ln extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <rect x="18.028" y="17.5" width="2" height="13"/>
                    <path d="M29.52,21.533c-0.659-1.221-1.97-2.05-3.455-2.05c-1.484,0-2.843,0.83-3.502,2.05c-0.297,0.55-0.535,1.18-0.535,1.85V30.5
                        h2v-7.118c0-1.16,0.84-2.1,2-2.1s2,0.94,2,2.1V30.5h2v-7.118C30.028,22.713,29.816,22.083,29.52,21.533z"/>
                </g>
            </svg>;
    }
}

module.exports = Ln;
