/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Middlebrackets extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <polygon points="15.5,15.5 15.5,17.412 15.5,29.412 15.5,31.5 18.1,31.5 20.5,31.5 20.5,29.5 17.5,29.5 17.5,17.5 20.5,17.5 
                        20.5,15.5 18.1,15.5 		"/>
                    <polygon points="30.1,15.5 26.5,15.5 26.5,17.5 29.5,17.5 29.5,29.5 26.5,29.5 26.5,31.5 30.1,31.5 31.5,31.5 31.5,29.412 
                        31.5,17.412 31.5,15.5 		"/>
                </g>
			</svg>
        )
    }
}

module.exports = Middlebrackets;
