/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Mu extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M27,16.5v6.112c0,1.657-1.343,3-3,3s-3-1.343-3-3V16.5h-2v6.112V31.5h2v-5.144c1.2,0.66,1.864,1.056,3,1.056
	s2.4-0.397,3-1.056V27.5h2v-4.888V16.5H27z"/>
			</svg>
        )
    }
}

module.exports = Mu;
