/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Neq extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                <rect x="13.5" y="13.5" display="none" opacity="0.2" width="20" height="20"/>
                <rect x="7.5" y="7.5" display="none" opacity="0.2" width="32" height="32"/>
                <polygon points="18.469,29.5 30.852,17.377 29.579,16.126 15.5,29.5 15.5,29.5 15.5,31.5 31.5,31.5 31.5,29.5 	"/>	
			</svg>
        )
    }
}

module.exports = Neq;
