/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Notin extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M31.649,18.178v-1.8h-1.411l1.357-2.351l-1.559-0.9l-1.877,3.251h-3.76c-4.169,0-7.599,3-8.047,7.2v1.8
                    c0.258,2.417,1.507,4.433,3.313,5.712l-1.665,2.883l1.559,0.9l1.684-2.917c0.971,0.399,2.035,0.622,3.156,0.622h7.25v-1.8h-7.325
                    c-0.764,0-1.495-0.143-2.17-0.399l2.888-5.001h6.607v-1.8H26.08l3.118-5.4C29.199,18.178,31.649,18.178,31.649,18.178z
                    M20.58,29.505c-1.295-0.988-2.196-2.464-2.42-4.127h4.803L20.58,29.505z M24.002,23.578H18.16c0.405-3,3.007-5.4,6.164-5.4h2.796
                    L24.002,23.578z"/>
			</svg>
        )
    }
}

module.exports = Notin;
