/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Nu extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M28.399,17.458c-0.28,1-0.705,1.568-1.065,2.269c-1.71,3.325-3.665,6.127-6.665,7.831v-4.873v-2.214v-0.9
                    c0-0.994-0.567-2.112-1.562-2.112h-0.9h-0.538v0.343v1.656h0.538c0.497,0,0.462,0.515,0.462,1.012v0.9v1.635v0.165v5.439v0.561
                    v1.373c4-1.576,7.709-5.217,10.166-9.994c0.5-0.971,1.142-2.092,1.496-3.092L28.399,17.458L28.399,17.458z"/>
			</svg>
        )
    }
}

module.exports = Nu;
