/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Omega extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M30.972,23.575c0-4.318-3.097-7.723-6.917-7.723s-6.917,3.357-6.917,7.675c0,2.286,0.871,5.62,2.256,6.62h-1.949v2h3.918
                    h1.082v-1.465c0-0.038-0.505-0.091-0.68-0.151c-2.123-0.73-2.749-4.03-2.749-6.764c0-3.322,2.252-6.015,5.076-6.015
                    s5.094,2.693,5.094,6.015c0,2.734-0.819,6.034-2.942,6.764c-0.175,0.06-0.243,0.109-0.799,0.151v1.465h1.303h3.697v-2h-1.728
                    C30.101,29.147,30.972,25.861,30.972,23.575z"/>
			</svg>
        )
    }
}

module.exports = Omega;
