/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class One extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24,15.484c-4.694,0-8.5,3.806-8.5,8.5s3.806,8.5,8.5,8.5s8.5-3.806,8.5-8.5S28.694,15.484,24,15.484z M24,31.225
                    c-3.999,0-7.241-3.242-7.241-7.241s3.242-7.241,7.241-7.241s7.241,3.242,7.241,7.241S27.999,31.225,24,31.225z M21.5,19.662v1.378
                    l2,0.146v8.298h2V19.186C25.5,19.186,21.5,19.483,21.5,19.662z"/>
			</svg>
        )
    }
}

module.exports = One;
