/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Overrightarrow extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M17.114,33.542h12v-12h-12V33.542z M18.914,23.341h8.4v8.4h-8.4V23.341z M27.206,20.141h1.686l2.994-3l-2.994-3h-1.686
	                l1.788,2h-12.88v2h12.88L27.206,20.141z"/>
			</svg>
        )
    }
}

module.exports = Overrightarrow;
