/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Parallel extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                    <rect x="13.5" y="12.5" display="none" opacity="0.2" width="20" height="21"/>
                    <rect x="7.5" y="6.5" display="none" opacity="0.2" width="32" height="33"/>
                    <g>
                        <polygon points="31.21,15.5 20.255,30.5 22.483,30.5 33.439,15.5 		"/>
                        <polygon points="25.116,15.5 14.161,30.5 16.39,30.5 27.345,15.5 		"/>
                    </g>
                </g>
			</svg>
        )
    }
}

module.exports = Parallel;
