/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Parenthesis extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M16.506,17.627v3.6c0,0.994,0.219,2.088-0.775,2.088h-1.225v2h1.225c0.994,0,0.775,0.318,0.775,1.312v3.6
                    c0,1.988,3,3.6,4,3.6v-1.8c0,0-2-0.806-2-1.8v-3.6c0-1.077-0.475-2.04-1.224-2.7c0.749-0.66,1.224-1.623,1.224-2.7v-3.6
                    c0-0.994,2-1.8,2-1.8v-1.8C19.506,14.027,16.506,15.639,16.506,17.627z M32.281,23.315c-0.994,0-0.775-1.094-0.775-2.088v-3.6
                    c0-1.988-3-3.6-4-3.6v1.8c0,0,2,0.806,2,1.8v3.6c0,1.077,0.475,2.04,1.224,2.7c-0.749,0.66-1.224,1.623-1.224,2.7v3.6
                    c0,0.994-2,1.8-2,1.8v1.8c1,0,4-1.612,4-3.6v-3.6c0-0.994-0.219-1.312,0.775-1.312h1.225v-2H32.281z"/>
			</svg>
        )
    }
}

module.exports = Parenthesis;
