/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Pi extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M25.823,26.775c0-1.08,0.108-4.449,0.13-6.846h-3.758c0,3.175-0.346,6.76-0.67,9.999l-2.505-0.129
		c0.561-3.304,0.842-6.846,0.842-9.87h-2.678V18.05l1.706-0.129h11.792v2.009H28.35c-0.151,2.505-0.173,6.025-0.173,6.976
		c0,0.842,0.367,1.145,1.102,1.145c0.216,0,0.518-0.043,0.929-0.108l0.302,1.857c-0.41,0.151-1.015,0.281-1.792,0.281
		C26.601,30.08,25.823,28.87,25.823,26.775z"/>
			</svg>
        )
    }
}

module.exports = Pi;
