/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Pm extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                <rect x="13.5" y="13.5" display="none" opacity="0.2" width="21" height="20"/>
                <rect x="7.5" y="6.5" display="none" opacity="0.2" width="33" height="34"/>
                <rect x="-0.5" y="-0.5" display="none" opacity="0.5" width="48" height="48"/>
                <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                <rect x="13.5" y="12.5" display="none" opacity="0.2" width="20" height="21"/>
                <rect x="7.5" y="6.5" display="none" opacity="0.2" width="32" height="33"/>
                <path display="none" d="M16.5,33.5h15v-1h-15V33.5z M25.5,22.5v-7h-2v7h-7v2h7v6h2v-6h6v-2H25.5z"/>
                <rect x="23" y="14.76" width="2" height="15"/>
                <rect x="16.5" y="21.26" width="15" height="2"/>
                <rect x="16.5" y="31.5" width="15" height="2"/>
			</svg>
        )
    }
}

module.exports = Pm;
