/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Huo extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M31.459,29.368v1.512H16.541v-1.512h2.571V17.121h9.996v12.247H31.459z M20.658,18.615v2.554h6.837v-2.554H20.658z
		            M27.495,22.614h-6.837v2.621h6.837V22.614z M20.658,29.368h6.837v-2.621h-6.837V29.368z"/>
			</svg>
        )
    }
}

module.exports = Huo;
