/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Rho extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24.148,15.203c-2.794,0-5.489,1.994-5.977,5.594l0,0v12h2v-6.383c1,1.111,2.428,1.796,3.939,1.796
	c3.148,0,5.719-2.858,5.719-6.503S27.296,15.203,24.148,15.203z M24.148,26.409c-2.154,0-3.9-2.149-3.9-4.8
	c0-2.651,1.746-4.8,3.9-4.8s3.9,2.149,3.9,4.8C28.048,24.26,26.302,26.409,24.148,26.409z"/>
			</svg>
        )
    }
}

module.exports = Rho;
