/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Righttopbtm extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M14.3,32.487h13.338V19.15H14.3V32.487z M15.512,20.362h10.912v10.913H15.512V20.362z M28.85,15.512v4.85h4.85v-4.85H28.85
		            z M32.487,19.15h-2.425v-2.425h2.425V19.15z M28.85,27.638v4.85h4.85v-4.85H28.85z M32.487,31.275h-2.425V28.85h2.425V31.275z"/>
			</svg>
        )
    }
}

module.exports = Righttopbtm;
