/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Angle extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <path d="M14.3,32.487h13.338V19.15H14.3V32.487z M15.512,20.362h10.912v10.913H15.512V20.362z M28.85,27.575v4.85h4.85v-4.85H28.85
                        z M32.487,31.212h-2.425v-2.425h2.425V31.212z"/>
                </g>	
			</svg>
        )
    }
}

module.exports = Angle;
