/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Rightleft extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M21.5,15.55c-0.292-0.09-0.592-0.142-0.9-0.142c-2.665,0-4.825,3.538-4.825,7.902s2.16,7.902,4.825,7.902
                    c0.308,0,0.608-0.052,0.9-0.142c-2.234-0.691-3.925-3.9-3.925-7.76S19.266,16.241,21.5,15.55z"/>
                <polygon points="29.575,15.5 26.5,15.5 26.5,17.5 29.5,17.5 29.5,29.5 26.5,29.5 26.5,31.5 29.575,31.5 31.5,31.5 31.5,29.412 
                    31.5,17.412 31.5,15.5 	"/>
			</svg>
        )
    }
}

module.exports = Rightleft;
