/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Sigma extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M30.506,18.3l-4.881-0.28l0,0c-0.6-0.394-1.562-0.62-2.421-0.62c-3.148,0-5.71,2.955-5.71,6.6s2.547,6.6,5.695,6.6
	s5.697-2.805,5.697-6.45c0-1.596-0.663-3.769-1.477-4.369l3.097,0.319V18.3z M23.183,28.8c-2.154,0-3.9-2.149-3.9-4.8
	s1.746-4.8,3.9-4.8s3.9,2.149,3.9,4.8C27.083,26.651,25.337,28.8,23.183,28.8z"/>
			</svg>
        )
    }
}

module.exports = Sigma;
