/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Sim extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M31.555,21.965c-0.586,1-2.128,2.231-3.944,2.231c-1.09,0-2.077-0.235-2.822-0.771c0.001,0,0.001,0.015,0.001,0.015
	c-0.815-0.682-1.857-1.217-3.024-1.415c-0.001-0.004-0.001-0.061-0.002-0.061h-0.092c-0.352,0-0.713-0.031-1.083-0.031
	c-0.371,0-0.733-0.095-1.085-0.041c-2.486,0.388-4.434,2.073-4.836,4.073h1.853c0.461-1,2.104-2.331,4.066-2.331
	c1.18,0,2.238,0.393,3,1.008c0.788,0.609,1.759,1.088,2.845,1.272c0.381,0.064,0.774,0.063,1.177,0.063
	c2.858,0,5.245-1.011,5.849-4.011L31.555,21.965L31.555,21.965z"/>
			</svg>
        )
    }
}

module.exports = Sim;
