/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Subset extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M33.516,19H21.692c-2.973,0-5.382,2.027-5.382,5s2.41,5,5.382,5h11.824v2H21.692c-3.963,0-7.176-3.037-7.176-7
	                s3.213-7,7.176-7h11.824V19z"/>
			</svg>
        )
    }
}

module.exports = Subset;
