/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Subsetneqq extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M21.781,17.1H30.9v-1.8h-9.494c-2.299,0-4.306,1.776-4.306,4.075v0.075c0,2.299,2.008,4.25,4.306,4.25H30.9v-1.8h-9.119
                    c-1.616,0-2.881-1.025-2.881-2.464v-0.047C18.9,17.949,20.165,17.1,21.781,17.1z M29.017,24.9h-2.546l-1.2,1.2H17.1v1.8h6.371
                    l-1.8,1.8H17.1v1.8h2.771l-1.2,1.2h2.546l1.2-1.2H30.9v-1.8h-6.683l1.8-1.8H30.9v-1.8h-3.083L29.017,24.9z"/>
			</svg>
        )
    }
}

module.exports = Subsetneqq;
