/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Subseteq extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M22.348,17.5H32v-2h-9.823c-3.314,0-6,2.686-6,6s2.686,6,6,6H32v-2h-9.652C20.079,25.5,18,23.773,18,21.503v-0.182
	                C18,19.052,20.078,17.5,22.348,17.5z M16,32.5h16v-2H16V32.5z"/>
			</svg>
        )
    }
}

module.exports = Subseteq;
