/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Supsetneqq extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M29.1,19.389v0.047c0,1.44-1.265,2.464-2.881,2.464H17.1v1.8h9.494c2.299,0,4.306-1.951,4.306-4.25v-0.075
                    c0-2.299-2.008-4.075-4.306-4.075H17.1v1.8h9.119C27.835,17.1,29.1,17.949,29.1,19.389z M29.017,24.9h-2.546l-1.2,1.2H17.1v1.8
                    h6.371l-1.8,1.8H17.1v1.8h2.771l-1.2,1.2h2.546l1.2-1.2H30.9v-1.8h-6.683l1.8-1.8H30.9v-1.8h-3.083L29.017,24.9z"/>
			</svg>
        )
    }
}

module.exports = Supsetneqq;
