/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Supset extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M14.25,19h12.324c2.973,0,5.382,2.027,5.382,5s-2.41,5-5.382,5H14.25v2h12.324c3.963,0,7.176-3.037,7.176-7
	s-3.213-7-7.176-7H14.25V19z"/>
			</svg>
        )
    }
}

module.exports = Supset;
