/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Supseteq extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M30,21.321v0.182c0,2.269-2.078,3.997-4.348,3.997H16v2h9.823c3.314,0,6-2.686,6-6s-2.686-6-6-6H16v2h9.652
	                C27.922,17.5,30,19.052,30,21.321z M32,30.5H16v2h16V30.5z"/>
			</svg>
        )
    }
}

module.exports = Supseteq;
