/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Cos1 extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg viewBox="0 0 1000 1000" width="48" height="48"><path d="M665.6 360.96c-12.8-7.68-28.16-2.56-35.84 10.24l-163.84 284.16-92.16-84.48c-10.24-10.24-25.6-10.24-35.84 0-10.24 10.24-10.24 25.6 0 35.84l117.76 107.52c10.24 10.24 25.6 10.24 35.84 0 2.56-2.56 184.32-317.44 184.32-317.44 7.68-12.8 2.56-28.16-10.24-35.84zM819.2 128H204.8C148.48 128 102.4 174.08 102.4 230.4v614.4c0 56.32 46.08 102.4 102.4 102.4h614.4c56.32 0 102.4-46.08 102.4-102.4V230.4c0-56.32-46.08-102.4-102.4-102.4z m51.2 716.8c0 28.16-23.04 51.2-51.2 51.2H204.8c-28.16 0-51.2-23.04-51.2-51.2V230.4c0-28.16 23.04-51.2 51.2-51.2h614.4c28.16 0 51.2 23.04 51.2 51.2v614.4z" fill="#403939"></path></svg>;
    }
}

module.exports = Cos1;
