/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Temperature extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M17.907,15.71c-1.646,0-2.98,1.334-2.98,2.98c0,1.646,1.334,2.98,2.98,2.98c1.646,0,2.98-1.334,2.98-2.98
                    C20.887,17.044,19.553,15.71,17.907,15.71z M17.907,19.882c-0.658,0-1.192-0.534-1.192-1.192c0-0.658,0.534-1.192,1.192-1.192
                    c0.658,0,1.192,0.534,1.192,1.192C19.099,19.348,18.566,19.882,17.907,19.882z M31.515,28.793c-1.009,1.094-2.145,1.759-3.647,1.759
                    c-3.003,0-4.891-2.488-4.891-6.456c0-3.926,1.974-6.371,4.955-6.371c1.351,0,2.402,0.622,3.218,1.502l1.073-1.287
                    c-0.901-1.008-2.402-1.952-4.312-1.952c-3.99,0-6.971,3.089-6.971,8.173c0,5.105,2.939,8.13,6.843,8.13
                    c2.038,0,3.582-0.815,4.826-2.252L31.515,28.793z"/>
			</svg>
        )
    }
}

module.exports = Temperature;
