/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Theta extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M28.804,24c0-4.639-2.149-8.4-4.8-8.4s-4.8,3.761-4.8,8.4s2.149,8.4,4.8,8.4S28.804,28.639,28.804,24z M21.06,25.088h5.889
                    c-0.266,3-1.483,5.103-2.944,5.103S21.326,28.088,21.06,25.088z M26.989,23.088h-5.971c0.145-3,1.426-5.697,2.985-5.697
                    S26.845,20.088,26.989,23.088z"/>
			</svg>
        )
    }
}

module.exports = Theta;
