/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Threeterm extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
				<path d="M20.5,16.5v4.8c0,0.994-1.281,2.088-2.275,2.088H17.5v2h0.725c0.994,0,2.275,0.318,2.275,1.312v4.8c0,1.988,1,3.6,3,3.6
                    v-1.8c-1,0-1-0.806-1-1.8v-4.8c0-1.077-0.475-2.04-1.224-2.7c0.749-0.66,1.224-1.623,1.224-2.7v-4.8c0-0.994,0-1.8,1-1.8v-1.8
                    C21.5,12.9,20.5,14.512,20.5,16.5z M25.5,14.388v5h5v-5H25.5z M29.5,18.388h-3v-3h3V18.388z M25.5,26.388h5v-5h-5V26.388z
                    M26.5,22.388h3v3h-3V22.388z M25.5,33.388h5v-5h-5V33.388z M26.5,29.388h3v3h-3V29.388z"/>
			</svg>
        )
    }
}

module.exports = Threeterm;
