/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Triangle extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M23.857,17.269L16.039,30.5h15.637L23.857,17.269z M23.865,20.682l4.503,7.818h-9.021L23.865,20.682z"/>
			</svg>
        )
    }
}

module.exports = Triangle;
