/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Two extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M24.076,15.484c-4.694,0-8.5,3.806-8.5,8.5c0,4.694,3.806,8.5,8.5,8.5c4.694,0,8.5-3.806,8.5-8.5
	C32.576,19.29,28.77,15.484,24.076,15.484z M24.076,31.225c-3.999,0-7.241-3.242-7.241-7.241c0-3.999,3.242-7.241,7.241-7.241
	c3.999,0,7.241,3.242,7.241,7.241S28.075,31.225,24.076,31.225z M23.663,27.64c1.891-1.849,3.446-3.866,3.446-5.743
	c0-1.933-1.303-3.193-3.264-3.193c-1.415,0-2.339,0.56-3.292,1.569l1.121,1.121c0.518-0.575,1.148-1.065,1.905-1.065
	c0.98,0,1.555,0.63,1.555,1.681c0,1.597-1.667,3.544-4.482,6.065v1.19h6.948v-1.737h-2.255
	C24.868,27.528,24.181,27.584,23.663,27.64z"/>
			</svg>
        )
    }
}

module.exports = Two;
