/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Twoterm extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
				<g>
                <path d="M17.5,17.2v3.6c0,0.994-0.506,1.7-1.5,1.7h-0.5v2H16c0.994,0,1.5,0.706,1.5,1.7v3.6c0,1.988,2,3.6,4,3.6v-1.8
                    c-1,0-2-0.806-2-1.8v-3.6c0-1.077-0.475-2.04-1.224-2.7c0.749-0.66,1.224-1.623,1.224-2.7v-3.6c0-0.994,1-1.8,2-1.8v-1.8
                    C19.5,13.6,17.5,15.212,17.5,17.2z M23.5,15.5v7h7v-7H23.5z M29.5,21.5h-5v-5h5V21.5z M23.5,32.5h7v-7h-7V32.5z M24.5,26.5h5v5h-5
                    V26.5z"/>
				</g>
			</svg>
        )
    }
}

module.exports = Twoterm;
