/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Upsilon extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
				<path d="M29.596,17.11h-0.558h-1.335c0.83,2,1.296,3.968,1.296,6.612v1.6c0,2.154-1.846,3.9-4,3.9s-4-1.746-4-3.9v-6.7
                    c0-0.95-0.619-1.576-1.553-1.643C19.448,16.975,17,17.283,17,17.283v1.827h1.544h0.004h0.004c0.463,0,0.448-0.133,0.448,0.319v5.893
                    c0,2.356,1.649,4.377,3.688,5.246c0.685,0.292,1.549,0.454,2.341,0.454c0.79,0,1.678-0.161,2.362-0.452
                    c2.042-0.867,3.61-2.89,3.61-5.248v-1.6C31,21.164,30.378,19.11,29.596,17.11z"/>
			</svg>
        )
    }
}

module.exports = Upsilon;
