/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Varnothing extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <path d="M32.592,16.951l-1.273-1.273l-1.768,1.768c-1.503-1.412-3.52-2.283-5.744-2.283c-4.639,0-8.4,3.761-8.4,8.4
                    c0,2.225,0.871,4.242,2.283,5.744l-2.068,2.068l1.273,1.273l2.161-2.161c1.352,0.929,2.987,1.476,4.751,1.476
                    c4.639,0,8.4-3.761,8.4-8.4c0-1.764-0.546-3.4-1.476-4.751L32.592,16.951z M17.208,23.564c0-3.645,2.955-6.6,6.6-6.6
                    c1.728,0,3.295,0.669,4.472,1.756l-9.316,9.316C17.876,26.859,17.208,25.291,17.208,23.564z M30.407,23.564
                    c0,3.645-2.955,6.6-6.6,6.6c-1.265,0-2.443-0.362-3.447-0.98l9.068-9.068C30.044,21.12,30.407,22.298,30.407,23.564z"/>
            </svg>;
    }
}

module.exports = Varnothing;
