/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Vee extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <polygon points="28.972,16 24.006,29.647 19.033,16 17.116,16 23.229,32 24.767,32 24.954,31.868 30.884,16 "/>
            </svg>;
    }
}

module.exports = Vee;
