/**
 * An autogenerated component that renders the COS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Vertical extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g>
                    <rect x="-0.5" y="-0.5" display="none" opacity="0.2" width="48" height="48"/>
                    <rect x="13.5" y="13.5" display="none" opacity="0.2" width="21" height="20"/>
                    <rect x="7.5" y="6.5" display="none" opacity="0.2" width="33" height="34"/>
                    <path d="M31.5,29.5v2h-15v-2h7v-14h2v14H31.5z"/>
                    <rect x="-0.5" y="-0.5" display="none" opacity="0.5" width="48" height="48"/>
                </g>
			</svg>
        )
    }
}

module.exports = Vertical;
