/**
 * An autogenerated component that renders the LN iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require('react');

class Wedge extends React.Component {
    static propTypes = {
        color: React.PropTypes.string.isRequired,
    };

    render() {
        return <svg width="48" height="48" viewBox="0 0 48 48">
                <polygon points="28.972,32 24.006,18.353 19.033,32 17.116,32 23.229,16 24.767,16 24.955,16.132 30.885,32 "/>
            </svg>;
    }
}

module.exports = Wedge;
